version: '3'
services:
  currency_converter_back:
    image: "madsum/currency_converter_back"
    ports:
      - "8080:8080"
    container_name: currency_converter_back
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    container_name: grafana